(require 'dash)
(require 'ht)
(require 's)

(setq *phrases*
      (ht
       (:cat1 (ht (:title "Establishing why your topic X is important")
                  (:items (list
                           (ht (:id 1)
                               (:template "X is the [{1}] cause of ...")
                               (:choices '(("main" "leading" "primary" "major"))))
                           (ht (:id 2)
                               (:template "Xs are a [{1}] part of ...")
                               (:choices '(("common" "useful" "critical"))))
                           (ht (:id 3)
                               (:template "Xs are among the most [{1}] types of ...")
                               (:choices '(("widely used" "commonly discussed" "well-known" "well-documented" "widespread" "commonly investigated"))))
                           (ht (:id 4)
                               (:template "X is [{1}] the most important ...")
                               (:choices '(("is recognized as being" "believed to be" "widely considered to be"))))
                           (ht (:id 5)
                               (:template "It is [{1}] that X is ...")
                               (:choices '(("well known" "generally accepted" "common knowledge"))))
                           (ht (:id 6)
                               (:template "X [{1}] a vital factor in ...")
                               (:choices '(("is increasingly becoming" "set to become"))))
                           (ht (:id 7)
                               (:template "Xs are [{1}] in terms of ...")
                               (:choices '(("undergoing a revolution" "generating considerable interest"))))
                           (ht (:id 8)
                               (:template "Xs are attracting [{1}] interest due to ...")
                               (:choices '(("considerable" "increasing" "widespread"))))
                           (ht (:id 9)
                               (:template "X has many [{1}] in the field of ...")
                               (:choices '(("uses" "roles" "applications"))))
                           (ht (:id 10)
                               (:template "A [{1}] feature of ...")
                               (:choices '(("striking" "useful" "remarkable"))))
                           (ht (:id 11)
                               (:template "The [{1}] characteristics of X are:")
                               (:choices '(("main" "principal" "fundamental"))))
                           (ht (:id 12)
                               (:template "X [{1}] for")
                               (:choices '(("accounts" "is responsible"))))))))

       (:cat2 (ht (:title "Outlining the past-present history of the study of X")
                  (:items (list
                           (ht (:id 13)
                               (:template "Last century X [{1}] the most ...")
                               (:choices '(("was considered to be" "viewed as" "seen as"))))
                           (ht (:id 14)
                               (:template "[{1}] studies of X considered it to be")
                               (:choices '(("Initial" "Preliminary" "The first"))))
                           (ht (:id 15)
                               (:template "[{1}], the focus has always been ...")
                               (:choices '(("Traditionally X" "In the history of X"))))
                           (ht (:id 16)
                               (:template "[{1}] have always seen X as ...")
                               (:choices '(("Scientists" "Researchers" "Experts"))))
                           (ht (:id 17)
                               (:template "[{1}] Xs have been considered as ...")
                               (:choices '(("Until now" "For many years" "Since 1942"))))
                           (ht (:id 18)
                               (:template "X has received much attention in the [{1}] ...")
                               (:choices '(("last two years" "in the past decade" "over the last two decades"))))
                           (ht (:id 19)
                               (:template "[{1}] there has been a rapid rise in the use of Xs")
                               (:choices '(("For the past five years" "Since 1942"))))
                           (ht (:id 20)
                               (:template "The last two years have [{1}] a huge growth in X ...")
                               (:choices '(("witnessed" "seen"))))
                           (ht (:id 21)
                               (:template "The [{1}] has seen a renewed importance in X ...")
                               (:choices '(("past decade" "last year"))))
                           (ht (:id 22)
                               (:template "Recent [{1}] X have led to ...")
                               (:choices '(("developments in" "findings regarding"))))
                           (ht (:id 23)
                               (:template "X has become a [{1}] issue in ...")
                               (:choices '(("central" "an important" "a critical"))))))))

       (:cat3 (ht (:title "Outlining the possible future of X")
                  (:items (list
                           (ht (:id 24)
                               (:template "The next decade is likely to [{1}] a considerable rise in X")
                               (:choices '(("see" "witness"))))
                           (ht (:id 25)
                               (:template "In the next few years X [{1}]")
                               (:choices '(("will become" "is likely to have become"))))
                           (ht (:id 26)
                               (:template "Within the next few years, X is [{1}] to become an important component in ...")
                               (:choices '(("set" "destined" "likely"))))
                           (ht (:id 27)
                               (:template "[{1}], X will have become ...")
                               (:choices '(("By 2042" "Within the next ten years"))))
                           (ht (:id 28)
                               (:template "X will [{1}] be an issue that ...")
                               (:choices '(("soon" "shortly" "rapidly" "inevitably"))))))))

       (:cat4 (ht (:title "Indicating the gap in knowledge and possible limitations")
                  (:items (list
                           (ht (:id 29)
                               (:template "Few researchers have addressed the [{1}] of ...")
                               (:choices '(("problem" "issue" "question"))))
                           (ht (:id 30)
                               (:template "Previous work has only [{1}] address ...")
                               (:choices '(("focused on" "been limited to" "failed to"))))
                           (ht (:id 31)
                               (:template "A [{1}] issue of ...")
                               (:choices '(("basic" "common" "fundamental" "crucial" "major"))))
                           (ht (:id 32)
                               (:template "The [{1}] problem of")
                               (:choices '(("central" "core"))))
                           (ht (:id 33)
                               (:template "[{1}] area in the field of ...")
                               (:choices '(("A challenging" "An intriguing" "An important" "A neglected"))))
                           (ht (:id 34)
                               (:template "Current solutions to X are [{1}]")
                               (:choices '(("inconsistent" "inadequate" "incorrect" "ineffective" "inefficient" "over-simplistic" "unsatisfactory"))))
                           (ht (:id 35)
                               (:template "Many hypotheses regarding X appear to be [{1}]")
                               (:choices '(("ill-defined" "unfounded" "not well grounded" "unsupported" "questionable" "disputable" "debatable"))))
                           (ht (:id 36)
                               (:template "The characteristics of X [{1}].")
                               (:choices '(("are not well understood" "are misunderstood" "have not been dealt with in depth"))))
                           (ht (:id 37)
                               (:template "It [{1}] whether X can do Y.")
                               (:choices '(("is not yet known" "has not yet been established"))))
                           (ht (:id 38)
                               (:template "X is still [{1}] understood.")
                               (:choices '(("poorly" "not widely"))))
                           (ht (:id 39)
                               (:template "X is often [{1}] ...")
                               (:choices '(("impractical" "not feasible" "costly"))))
                           (ht (:id 40)
                               (:template "Techniques to solve X are [{1}].")
                               (:choices '(("computationally demanding" "subject to high overheads" "time consuming" "impractical" "frequently unfeasible"))))
                           (ht (:id 41)
                               (:template "A major [{1}] of X is ...")
                               (:choices '(("defect" "difficulty" "drawback" "disadvantage" "flaw"))))
                           (ht (:id 42)
                               (:template "One of the main issues in [{1}] X is a lack of ...")
                               (:choices '(("our knowledge of" "what we know about"))))
                           (ht (:id 43)
                               (:template "This [{1}] area of X [{2}] ...")
                               (:choices '(("particular" "specific") ("has been overlooked" "has been neglected" "remains unclear"))))
                           (ht (:id 44)
                               (:template "Despite this interest, no one [{1}] has studied ...")
                               (:choices '(("to the best of our knowledge" "as far as we know"))))
                           (ht (:id 45)
                               (:template "Although this approach is interesting, it [{1}] ...")
                               (:choices '(("suffers from" "fails to take into account" "does not allow for"))))
                           (ht (:id 46)
                               (:template "[{1}] its shortcomings, this method has been widely applied to ...")
                               (:choices '(("In spite of" "Despite"))))
                           (ht (:id 47)
                               (:template "However, there [{1}] ...")
                               (:choices '(("is still a need for" "has been little discussion on"))))
                           (ht (:id 48)
                               (:template "Moreover, other [{1}] have failed to provide ...")
                               (:choices '(("solutions" "research programs" "approaches"))))
                           (ht (:id 49)
                               (:template "Most studies [{1}] focus on ...")
                               (:choices '(("have only focused" "tended to"))))
                           (ht (:id 50)
                               (:template "[{1}] this methodology has only been applied to ...")
                               (:choices '(("To date" "Until now"))))
                           (ht (:id 51)
                               (:template "There is still [{1}] controversy surrounding ...")
                               (:choices '(("some" "much" "considerable"))))
                           (ht (:id 52)
                               (:template "There has been some disagreement [{1}] whether")
                               (:choices '(("concerning" "regarding" "with regard to"))))
                           (ht (:id 53)
                               (:template "There is [{1}] on ...")
                               (:choices '(("little" "no general agreement"))))
                           (ht (:id 54)
                               (:template "The community has raised some [{1}] about ...")
                               (:choices '(("issues" "concerns"))))
                           (ht (:id 55)
                               (:template "Concerns have [{1}] which [{2}] the validity of ...")
                               (:choices '(("arisen" "been raised") ("question" "call into question"))))
                           (ht (:id 56)
                               (:template "In the light of recent events in x, there is now [{1}] concern about ...")
                               (:choices '(("some" "much" "considerable"))))))))

       (:cat5 (ht (:title "Stating the aim of your paper and its contribution")
                  (:items (list
                           (ht (:id 57)
                               (:template "In this [{1}] we ...")
                               (:choices '(("report" "paper" "review" "study"))))
                           (ht (:id 58)
                               (:template "This paper [{1}] a new approach to ...")
                               (:choices '(("outlines" "proposes" "describes" "presents"))))
                           (ht (:id 59)
                               (:template "This paper [{1}] how to solve ...")
                               (:choices '(("examines" "seeks to address" "focuses on" "discusses" "investigates"))))
                           (ht (:id 60)
                               (:template "This paper is [{1}] ...")
                               (:choices '(("an overview of" "a review of" "a report on" "a preliminary attempt to"))))
                           (ht (:id 61)
                               (:template "The present paper aims to [{1}] Marvin’s findings regarding ...")
                               (:choices '(("validate" "call into question" "refute"))))
                           (ht (:id 62)
                               (:template "X is [{1}] in order to ...")
                               (:choices '(("presented" "described" "analyzed" "computed" "investigated" "examined" "introduced" "discussed"))))
                           (ht (:id 63)
                               (:template "The aim of our [{1}] was to [{2}] current knowledge of ...")
                               (:choices '(("work" "research" "study" "analysis") ("further" "extend" "widen" "broaden"))))
                           (ht (:id 64)
                               (:template "Our knowledge of X is largely based on very limited data. The aim of the research was [{1}] to")
                               (:choices '(("thus" "therefore" "consequently"))))
                           (ht (:id 65)
                               (:template "The aim of this study is to [{1}] ...")
                               (:choices '(("study" "evaluate" "validate" "determine" "examine" "analyze" "calculate" "estimate" "formulate"))))
                           (ht (:id 66)
                               (:template "This paper [{1}] ...")
                               (:choices '(("calls into question" "takes a new look at" "re-examines" "revisits" "sheds new light on"))))
                           (ht (:id 67)
                               (:template "[{1}], we tried to ...")
                               (:choices '(("With this in mind" "Within the framework of these criteria" "In this context"))))
                           (ht (:id 68)
                               (:template "We [{1}] to ...")
                               (:choices '(("undertook this study" "initiated this research" "developed this methodology"))))
                           (ht (:id 69)
                               (:template "We believe that we have [{1}] an innovative solution to ...")
                               (:choices '(("found" "developed" "discovered" "designed"))))
                           (ht (:id 70)
                               (:template "We [{1}] solution for ...")
                               (:choices '(("describe" "present" "consider" "analyze a novel" "simple" "radical" "interesting"))))
                           (ht (:id 99)
                               (:template "")
                               (:choices '(())))))))))

(defun ht-get* (table &rest keys)
  (if (cdr keys)
      (apply #'ht-get* (ht-get table (car keys)) (cdr keys))
    (ht-get table (car keys))))

(defun ht-select-keys (table keys)
  "Return a copy of TABLE with only the specified KEYS."
  (let (result)
    (setq result (make-hash-table :test (hash-table-test table)))
    (dolist (key keys result)
      (if (not (equal (gethash key table 'key-not-found) 'key-not-found))
          (puthash key (gethash key table) result)))))

(defun replace-placeholders (tmp choices)
  (s-replace-all `(("{1}" . ,(s-join "/" (car choices)))
                   ("{2}" . ,(s-join "/" (cadr choices))))
                  tmp))

(defun prompt-categories (phrases)
  (ht-map (lambda (k v) (ht-get* phrases k :title))
          phrases))

(defun prompt-items (cat &optional phrases)
  "..."
  (unless phrases (setq phrases *phrases*))
  (mapcar (lambda (h)
           (cons (replace-placeholders
                   (ht-get h :template)
                   (ht-get h :choices))
            (ht-get h :id)))
         (get-items cat phrases)))

(defun filter-item (cat id &optional phrases)
  "..."
  (unless phrases (setq phrases *phrases*))
  (let* ((items (get-items cat phrases))
         (match (car (-filter (lambda (i)
                                (equal (ht-get i :id) id))
                              items))))
       match))

(defun get-cat (res &optional phrases)
  "..."
  (unless phrases (setq phrases *phrases*))
  (let ((item (ht-find (lambda (k v)
                         (equal (ht-get v :title)
                                res))
                       phrases)))
    (car item)))

(defun get-items (cat &optional phrases)
  "..."
  (unless phrases (setq phrases *phrases*))
  (ht-get* phrases cat :items))

(defun academic-phrases-insert (phrases)
  (let* ((res (completing-read "Choose category:"
                               (prompt-categories phrases) nil t))
         (cat (get-cat res phrases))
         (items (prompt-items cat))
         (id (cdr (assoc (completing-read "Choose a phrase:"
                                          items nil t)
                         items)))
         (item (filter-item cat id))
         (phrase-prompt (car (rassoc id items)))
         (template (ht-get item :template))
         (choice1 (completing-read phrase-prompt
                                   (car (ht-get item :choices))
                                   nil t))
         (choice2 (when (s-contains? "{2}" template)
                        (completing-read phrase-prompt
                                         (cadr (ht-get item :choices))
                                         nil t)))
         (phrase (s-replace-all `(("[{1}]" . ,choice1)
                                  ("[{2}]" . ,choice2))
                                 template)))
    (insert phrase)))

(defun academic-phrases-by-section (section &optional phrases)
  "..."
  (unless phrases (setq phrases *phrases*))
  (cond ((equal section :abstract) (setq cats '(:cat1 :cat3)))
        (t (setq cats '(:cat1 :cat2 :cat3 :cat4 :cat5))))
  (academic-phrases-insert (ht-select-keys phrases cats)))

(defun academic-phrases ()
  (interactive)
  (academic-phrases-insert *phrases*))
