* Academic-phrases

[[http://spacemacs.org][file:https://cdn.rawgit.com/syl20bnr/spacemacs/442d025779da2f62fc86c2082703697714db6514/assets/spacemacs-badge.svg]]


When writing your academic paper, you might get stuck trying to find the right
phrase that captures your intention. This package tries to alleviate that
problem by presenting you with a list of phrases organized by the topic or by
the paper section that you are writing. This package has around 600 phrases so
far.

Using this package is easy, just call =M-x academic-phrases= to get a list of
phrases organized by topic, or call =academic-phrases-by-section= to browse the
phrases by the paper section and fill-in the blanks if required.


** Demo
[[demo][./assets/academic-phrases.gif]]


** Acknowledgements

This work was based on the freely available PDF titled "English for Writing
Research - Papers Useful Phrases" which can be found here
<http://www.springer.com/gb/book/9783319260921>. This work was done with the
kind permission of Springer Nature and Adrian Wallwork.
